### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Manny-97** [BrightOsas/Youtube-data-pipeline#3]
### A comprehensive review of the project
- [x] No .env_sample file
- [x] Add .gitignore file
- [x] Remove exposed secrets from compose file
- [x] Consolidate all README.md files in root directory

**Comment by Manny-97** [comment]
@BrightOsas 
Can you give reasons why you added the dataset to the repository? Please explain below

**Comment by BrightOsas** [comment]
@Manny-97 no specific reasons to be precise, i tot it was okay to share the dataset

would remove them immediately.

Thank you.
